 [build]
  functions="src"
  [settings]
  node_version = "16"
[[redirects]]
   from = "/*"
  to = "/index.html"
  status = 200
 [functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

  