//export const host = "https://chatzak.onrender.com";
export const host = "http://localhost:5000";
export const loginRoute = `${host}/api/auth/login`;
export const registerRoute = `${host}/api/auth/register`;
export const allUsersRoute = `${host}/api/auth/all-users`;
export const sendMessageRoute = `${host}/api/messages/addmsg`;
export const getAllMessagesRoute = `${host}/api/messages/getMsg`;
export const createAvatarRoute = `https://api.dicebear.com/7.x/bottts/svg?seed=`
export const updateAvatarRoute = `${host}/api/auth/users/`;
export const getUserByIdRoute = `${host}/api/auth/users/`;
export const deleteMessageRoute = `${host}/api/messages/message/`